#!/usr/bin/env node
/**
 * @copyright 2024-2026 nirholas. All rights reserved.
 * @license SPDX-License-Identifier: SEE LICENSE IN LICENSE
 * @see https://github.com/nirholas/cryptocurrency.cv
 */

/**
 * Translated locales: the single source of truth is the set of `messages/<locale>.json`
 * files that actually exist on disk. Everything that advertises a translation to the
 * outside world (hreflang alternates, the sitemap, the SSG locale list, the i18n
 * tooling config) derives from this list so it can never drift from reality.
 *
 * `readTranslatedLocales()` reads the directory. `writeTranslatedLocalesModule()` emits
 * `src/i18n/translated-locales.generated.ts` so browser and serverless bundles get a
 * static constant instead of a runtime `fs` call. next.config.js calls the writer on
 * every build/dev start; it can also be run directly:
 *
 *   node scripts/lib/translated-locales.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const MESSAGES_DIR = path.join(ROOT, 'messages');
const OUTPUT = path.join(ROOT, 'src', 'i18n', 'translated-locales.generated.ts');

function readTranslatedLocales(messagesDir = MESSAGES_DIR) {
  return fs
    .readdirSync(messagesDir)
    .filter((file) => file.endsWith('.json'))
    .map((file) => file.slice(0, -'.json'.length))
    .filter((locale) => /^[a-z]{2,3}(-[A-Za-z]{2,4})?$/.test(locale))
    .sort();
}

function renderModule(locales) {
  const entries = locales.map((locale) => `  '${locale}',`).join('\n');
  return `/**
 * @copyright 2024-2026 nirholas. All rights reserved.
 * @license SPDX-License-Identifier: SEE LICENSE IN LICENSE
 * @see https://github.com/nirholas/cryptocurrency.cv
 */

/**
 * GENERATED FILE. Do not edit by hand.
 *
 * Locales that have a real translation file in \`messages/\`. Regenerated by
 * scripts/lib/translated-locales.js (invoked from next.config.js on every build).
 * Routing still accepts every locale in src/i18n/config.ts; this list is what the
 * site advertises to search engines as genuinely translated alternates.
 */

export const TRANSLATED_LOCALES = [
${entries}
] as const;

export type TranslatedLocale = (typeof TRANSLATED_LOCALES)[number];
`;
}

function writeTranslatedLocalesModule() {
  const locales = readTranslatedLocales();
  const next = renderModule(locales);
  const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : null;
  if (current !== next) {
    fs.writeFileSync(OUTPUT, next);
  }
  return locales;
}

module.exports = { readTranslatedLocales, writeTranslatedLocalesModule, MESSAGES_DIR, OUTPUT };

if (require.main === module) {
  const locales = writeTranslatedLocalesModule();
  console.log(`Wrote ${locales.length} translated locales to ${path.relative(ROOT, OUTPUT)}`);
}
