#!/usr/bin/env bash

# Copyright 2024-2026 nirholas. All rights reserved.
# SPDX-License-Identifier: SEE LICENSE IN LICENSE
# https://github.com/nirholas/free-crypto-news
#
# This file is part of free-crypto-news.
# Unauthorized copying, modification, or distribution is strictly prohibited.
# For licensing inquiries: nirholas@users.noreply.github.com

#
# Install / uninstall the quality-gate pre-push hook
#
# Usage:
#   ./scripts/install-pre-push-hook.sh           # install
#   ./scripts/install-pre-push-hook.sh --remove   # uninstall
#

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
GIT_DIR="$(git -C "$PROJECT_ROOT" rev-parse --git-dir 2>/dev/null)" || {
  echo -e "${RED}Error: not inside a git repository.${NC}" >&2
  exit 1
}
HOOK_PATH="$GIT_DIR/hooks/pre-push"

# ── Uninstall ────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--remove" || "${1:-}" == "--uninstall" ]]; then
  if [[ -f "$HOOK_PATH" ]] && grep -q "quality-gate" "$HOOK_PATH" 2>/dev/null; then
    rm "$HOOK_PATH"
    echo -e "${GREEN}✔ Pre-push hook removed.${NC}"
  else
    echo -e "${YELLOW}No quality-gate pre-push hook found — nothing to remove.${NC}"
  fi
  exit 0
fi

# ── Install ──────────────────────────────────────────────────────────────
mkdir -p "$(dirname "$HOOK_PATH")"

# Guard against overwriting a user-managed hook
if [[ -f "$HOOK_PATH" ]] && ! grep -q "quality-gate" "$HOOK_PATH" 2>/dev/null; then
  echo -e "${YELLOW}⚠  A pre-push hook already exists at:${NC}"
  echo "   $HOOK_PATH"
  echo -e "${YELLOW}   It does not appear to be the quality-gate hook.${NC}"
  echo -e "${YELLOW}   Rename or remove it first, then re-run this script.${NC}"
  exit 1
fi

cat > "$HOOK_PATH" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-pre-push-hook.sh — quality-gate pre-push hook

set -euo pipefail

echo ""
echo "🔒 Running quality gate before push…"
echo ""

REPO_ROOT="$(git rev-parse --show-toplevel)"

# Run the quality gate (skip E2E by default for speed; remove --skip-e2e for full checks)
"$REPO_ROOT/scripts/quality-gate.sh" --skip-e2e

echo ""
echo "✅ Quality gate passed — pushing."
echo ""
HOOK

chmod +x "$HOOK_PATH"

echo ""
echo -e "${GREEN}${BOLD:-}✔ Pre-push hook installed at:${NC}"
echo "   $HOOK_PATH"
echo ""
echo -e "${BLUE}The hook runs ${NC}scripts/quality-gate.sh --skip-e2e${BLUE} before each push.${NC}"
echo -e "${BLUE}Edit the hook to remove --skip-e2e for full E2E coverage.${NC}"
echo ""
echo -e "${YELLOW}To uninstall:${NC}  ./scripts/install-pre-push-hook.sh --remove"
echo ""
