{{- if .Values.web.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "free-crypto-news.fullname" . }}-web
  labels:
    {{- include "free-crypto-news.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.web.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "free-crypto-news.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
---
{{- if .Values.websocket.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "free-crypto-news.fullname" . }}-websocket
  labels:
    {{- include "free-crypto-news.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  minAvailable: {{ .Values.websocket.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "free-crypto-news.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: websocket
{{- end }}
